### ISSUE TITLE
Why the results far overtakes the state of DEC paper, 96.2% VS 84.3%?

### ISSUE THREAD

**Issue by whytin** [Tony607/Keras_Deep_Clustering#6]
Thanks your excellence work! It helps me a lot, and I  wonder why the why the results far overtakes the state of DEC paper, 96.2% VS 84.3%?  Is there any tricks in the experiment？

**Comment by endseeker** [comment]
is it because he is using weights as the centroids?
        self.clusters = self.add_weight((self.n_clusters, input_dim), initializer='glorot_uniform', name='clusters')

original DEC uses latent vectors from all inputs as the centroids from my understanding.
